"""Quiz content for every lesson, keyed by (phase_number, lesson_number).

Each question is a dict:
    {
      "type": "multiple-choice" | "fill-blank",
      "text": str,
      "options": [str, ...],        # [] for fill-blank
      "correct_answer": str,         # must equal one option for MC
      "explanation": str,            # shown after grading
    }

Fill-blank answers are graded case- and whitespace-insensitively.
"""

QUIZZES = {
    # ===== Phase 1: Python Fundamentals =====
    (1, 1): [
        {"type": "multiple-choice", "text": "What is the type of `3.0` in Python?",
         "options": ["int", "float", "str", "bool"], "correct_answer": "float",
         "explanation": "A numeric literal with a decimal point is a float."},
        {"type": "multiple-choice", "text": "Which value is immutable?",
         "options": ["list", "dict", "str", "set"], "correct_answer": "str",
         "explanation": "Strings are immutable; operations create new strings."},
        {"type": "fill-blank", "text": "The function that returns a value's type is ____ (name only).",
         "options": [], "correct_answer": "type",
         "explanation": "`type(x)` returns the class of x."},
    ],
    (1, 2): [
        {"type": "multiple-choice", "text": "What does `range(3)` produce?",
         "options": ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3", "3"], "correct_answer": "0, 1, 2",
         "explanation": "range(n) yields 0 .. n-1."},
        {"type": "multiple-choice", "text": "Which operator gives the remainder of a division?",
         "options": ["/", "//", "%", "**"], "correct_answer": "%",
         "explanation": "`%` is modulo (remainder). `//` is floor division."},
        {"type": "fill-blank", "text": "The keyword that exits a loop immediately is ____.",
         "options": [], "correct_answer": "break",
         "explanation": "`break` leaves the enclosing loop; `continue` skips to the next iteration."},
    ],
    (1, 3): [
        {"type": "multiple-choice", "text": "A function with no explicit `return` returns:",
         "options": ["0", "None", "an error", "the last expression"], "correct_answer": "None",
         "explanation": "Without a return statement, a function returns None."},
        {"type": "multiple-choice", "text": "In `def f(x, factor=2):`, `factor` is a:",
         "options": ["global variable", "default parameter", "keyword-only arg", "return value"],
         "correct_answer": "default parameter",
         "explanation": "It has a default value used when the caller omits it."},
        {"type": "fill-blank", "text": "Variables created inside a function have ____ scope.",
         "options": [], "correct_answer": "local",
         "explanation": "They don't leak outside the function."},
    ],
    (1, 4): [
        {"type": "multiple-choice", "text": "Which collection stores unique, unordered values?",
         "options": ["list", "tuple", "set", "dict"], "correct_answer": "set",
         "explanation": "A set holds unique elements with no order."},
        {"type": "multiple-choice", "text": "What does `[x*x for x in range(3)]` produce?",
         "options": ["[0, 1, 4]", "[1, 4, 9]", "[0, 1, 2]", "[1, 2, 3]"], "correct_answer": "[0, 1, 4]",
         "explanation": "Squares of 0, 1, 2."},
        {"type": "fill-blank", "text": "`dict.___(key, 0)` returns a default instead of raising KeyError.",
         "options": [], "correct_answer": "get",
         "explanation": "`d.get(key, default)` avoids KeyError."},
    ],
    # ===== Phase 2: DSA =====
    (2, 1): [
        {"type": "multiple-choice", "text": "A stack is:",
         "options": ["FIFO", "LIFO", "sorted", "random"], "correct_answer": "LIFO",
         "explanation": "Last in, first out."},
        {"type": "multiple-choice", "text": "For an efficient queue in Python, use:",
         "options": ["list.pop(0)", "collections.deque", "a set", "a tuple"],
         "correct_answer": "collections.deque",
         "explanation": "deque gives O(1) pops from the left; list.pop(0) is O(n)."},
        {"type": "fill-blank", "text": "Matching-bracket problems are naturally solved with a ____.",
         "options": [], "correct_answer": "stack",
         "explanation": "Push opens, pop on closes."},
    ],
    (2, 2): [
        {"type": "multiple-choice", "text": "Average lookup time in a dict is:",
         "options": ["O(1)", "O(log n)", "O(n)", "O(n^2)"], "correct_answer": "O(1)",
         "explanation": "Hash maps give average O(1) lookup."},
        {"type": "multiple-choice", "text": "Which cannot be a dict key?",
         "options": ["str", "int", "tuple", "list"], "correct_answer": "list",
         "explanation": "Keys must be hashable; lists are mutable and unhashable."},
        {"type": "fill-blank", "text": "The two-sum trick stores each value's ____ as you scan.",
         "options": [], "correct_answer": "index",
         "explanation": "Map value -> index so the complement can be found in O(1)."},
    ],
    (2, 3): [
        {"type": "multiple-choice", "text": "Every recursion must have a:",
         "options": ["loop", "base case", "global", "return None"], "correct_answer": "base case",
         "explanation": "Without a base case it never stops and overflows the stack."},
        {"type": "multiple-choice", "text": "Repeated recursive work is best fixed with:",
         "options": ["more recursion", "memoization", "a print", "a longer name"],
         "correct_answer": "memoization",
         "explanation": "Caching subresults avoids recomputation."},
        {"type": "fill-blank", "text": "Naive recursive Fibonacci has exponential ____ complexity.",
         "options": [], "correct_answer": "time",
         "explanation": "It recomputes the same subproblems repeatedly."},
    ],
    (2, 4): [
        {"type": "multiple-choice", "text": "Binary search requires the input to be:",
         "options": ["reversed", "sorted", "unique", "small"], "correct_answer": "sorted",
         "explanation": "It relies on order to discard half each step."},
        {"type": "multiple-choice", "text": "Binary search runs in:",
         "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"], "correct_answer": "O(log n)",
         "explanation": "It halves the search range each iteration."},
        {"type": "fill-blank", "text": "Python's built-in `____()` sorts and returns a new list.",
         "options": [], "correct_answer": "sorted",
         "explanation": "`sorted(iterable)` returns a new sorted list."},
    ],
    # ===== Phase 3: Math for AI =====
    (3, 1): [
        {"type": "multiple-choice", "text": "The dot product of [1,2,3] and [4,5,6] is:",
         "options": ["32", "21", "15", "90"], "correct_answer": "32",
         "explanation": "1*4 + 2*5 + 3*6 = 32."},
        {"type": "multiple-choice", "text": "A single neuron computes essentially a:",
         "options": ["sort", "dot product plus bias", "median", "hash"],
         "correct_answer": "dot product plus bias",
         "explanation": "output = dot(weights, inputs) + bias."},
        {"type": "fill-blank", "text": "A vector's length is the square root of its dot product with ____ (itself/zero).",
         "options": [], "correct_answer": "itself",
         "explanation": "norm(v) = sqrt(dot(v, v))."},
    ],
    (3, 2): [
        {"type": "multiple-choice", "text": "To multiply an (m x n) by a (p x q) matrix, you need:",
         "options": ["m == p", "n == p", "n == q", "m == q"], "correct_answer": "n == p",
         "explanation": "Inner dimensions must match: (m x n)(n x q)."},
        {"type": "multiple-choice", "text": "In general, matrix multiplication is:",
         "options": ["commutative", "not commutative", "always identity", "elementwise"],
         "correct_answer": "not commutative",
         "explanation": "A·B != B·A in general."},
        {"type": "fill-blank", "text": "`output = inputs @ weights` is the forward pass of a ____ layer.",
         "options": [], "correct_answer": "linear",
         "explanation": "Also called a dense/fully-connected layer."},
    ],
    (3, 3): [
        {"type": "multiple-choice", "text": "Population variance divides the squared deviations by:",
         "options": ["n", "n-1", "n+1", "sqrt(n)"], "correct_answer": "n",
         "explanation": "Sample variance uses n-1; population uses n."},
        {"type": "multiple-choice", "text": "Standard deviation is the ____ of the variance.",
         "options": ["square", "square root", "mean", "log"], "correct_answer": "square root",
         "explanation": "std = sqrt(variance), back in original units."},
        {"type": "fill-blank", "text": "Subtracting the mean and dividing by std produces a ____-score.",
         "options": [], "correct_answer": "z",
         "explanation": "The z-score standardizes to mean 0, std 1."},
    ],
    (3, 4): [
        {"type": "multiple-choice", "text": "A derivative measures a function's:",
         "options": ["area", "slope", "maximum", "average"], "correct_answer": "slope",
         "explanation": "It's the instantaneous rate of change."},
        {"type": "multiple-choice", "text": "The central difference formula uses f at:",
         "options": ["x only", "x and x+h", "x+h and x-h", "0 and x"],
         "correct_answer": "x+h and x-h",
         "explanation": "(f(x+h)-f(x-h))/(2h) is more accurate than one-sided."},
        {"type": "fill-blank", "text": "Training follows the ____ of the loss downhill.",
         "options": [], "correct_answer": "gradient",
         "explanation": "Gradient descent steps against the gradient."},
    ],
    # ===== Phase 4: Data Manipulation =====
    (4, 1): [
        {"type": "multiple-choice", "text": "Applying an op to a whole array at once is called:",
         "options": ["looping", "vectorization", "recursion", "hashing"],
         "correct_answer": "vectorization",
         "explanation": "NumPy operates on entire arrays without Python loops."},
        {"type": "multiple-choice", "text": "Compared to Python loops, vectorized NumPy is usually:",
         "options": ["slower", "the same", "much faster", "unavailable"],
         "correct_answer": "much faster",
         "explanation": "It runs in optimized C over compact arrays."},
        {"type": "fill-blank", "text": "A tensor is essentially a NumPy array with a GPU and ____ added.",
         "options": [], "correct_answer": "gradients",
         "explanation": "Frameworks add autograd (gradients) and device support."},
    ],
    (4, 2): [
        {"type": "multiple-choice", "text": "Standardized data has mean and std of:",
         "options": ["0 and 1", "1 and 0", "0 and 0", "1 and 1"], "correct_answer": "0 and 1",
         "explanation": "Subtract mean, divide by std -> mean 0, std 1."},
        {"type": "multiple-choice", "text": "Stretching a smaller array to combine with a larger one is:",
         "options": ["slicing", "broadcasting", "reshaping", "masking"],
         "correct_answer": "broadcasting",
         "explanation": "Broadcasting applies scalars/rows across an array."},
        {"type": "fill-blank", "text": "Fit scaling on the ____ set, then apply the same numbers to test.",
         "options": [], "correct_answer": "training",
         "explanation": "Using test statistics would leak information."},
    ],
    (4, 3): [
        {"type": "multiple-choice", "text": "Pandas' split-apply-combine operation is:",
         "options": ["merge", "groupby", "pivot", "concat"], "correct_answer": "groupby",
         "explanation": "groupby splits rows, applies a function, combines results."},
        {"type": "multiple-choice", "text": "A DataFrame is best described as:",
         "options": ["a single value", "a table of named columns", "a set", "a function"],
         "correct_answer": "a table of named columns",
         "explanation": "It's columns of aligned Series."},
        {"type": "fill-blank", "text": "Grouping raw events into per-user features is called feature ____.",
         "options": [], "correct_answer": "engineering",
         "explanation": "Aggregation is a core feature-engineering step."},
    ],
    (4, 4): [
        {"type": "multiple-choice", "text": "Replacing missing values with the column mean is called:",
         "options": ["dropping", "mean imputation", "scaling", "encoding"],
         "correct_answer": "mean imputation",
         "explanation": "Impute = fill missing with an estimate (here, the mean)."},
        {"type": "multiple-choice", "text": "A downside of mean imputation is that it:",
         "options": ["adds rows", "shrinks variance", "sorts data", "removes columns"],
         "correct_answer": "shrinks variance",
         "explanation": "Filling with the mean reduces spread."},
        {"type": "fill-blank", "text": "Most scikit-learn estimators reject values that are ____ (NaN/None).",
         "options": [], "correct_answer": "missing",
         "explanation": "You must impute or drop before fitting."},
    ],
    # ===== Phase 5: Visualization =====
    (5, 1): [
        {"type": "multiple-choice", "text": "A histogram shows a variable's:",
         "options": ["correlation", "distribution", "sort order", "type"],
         "correct_answer": "distribution",
         "explanation": "It counts values into bins to reveal shape."},
        {"type": "multiple-choice", "text": "Bin width equals:",
         "options": ["(max-min)/k", "max/k", "k/n", "min*k"], "correct_answer": "(max-min)/k",
         "explanation": "The range divided by the number of bins."},
        {"type": "fill-blank", "text": "Too ____ bins hide structure in a histogram.",
         "options": [], "correct_answer": "few",
         "explanation": "Too few bins over-smooth; too many add noise."},
    ],
    (5, 2): [
        {"type": "multiple-choice", "text": "Pearson correlation ranges from:",
         "options": ["0 to 1", "-1 to 1", "-inf to inf", "0 to 100"], "correct_answer": "-1 to 1",
         "explanation": "-1 perfect opposite, +1 perfect same direction."},
        {"type": "multiple-choice", "text": "Pearson's r captures which kind of association?",
         "options": ["any", "linear", "circular", "categorical"], "correct_answer": "linear",
         "explanation": "A U-shape can have r ~ 0 despite strong structure."},
        {"type": "fill-blank", "text": "Correlation does not imply ____.",
         "options": [], "correct_answer": "causation",
         "explanation": "Associated variables need not be causally linked."},
    ],
    (5, 3): [
        {"type": "multiple-choice", "text": "Min-max scaling maps values into:",
         "options": ["[-1, 1]", "[0, 1]", "[0, 255]", "mean 0"], "correct_answer": "[0, 1]",
         "explanation": "(x-min)/(max-min) is bounded to [0,1]."},
        {"type": "multiple-choice", "text": "Min-max scaling is sensitive to:",
         "options": ["column names", "outliers", "row order", "data types"],
         "correct_answer": "outliers",
         "explanation": "One extreme value squashes the rest of the range."},
        {"type": "fill-blank", "text": "Image pixels are often scaled from 0-255 down to 0-____.",
         "options": [], "correct_answer": "1",
         "explanation": "Divide by 255 to get the [0,1] range."},
    ],
    # ===== Phase 6: ML Fundamentals =====
    (6, 1): [
        {"type": "multiple-choice", "text": "The test set exists to:",
         "options": ["train faster", "evaluate on unseen data", "add features", "shuffle rows"],
         "correct_answer": "evaluate on unseen data",
         "explanation": "It estimates real-world generalization."},
        {"type": "multiple-choice", "text": "Letting test data influence training is called:",
         "options": ["leakage", "batching", "scaling", "pooling"], "correct_answer": "leakage",
         "explanation": "Data leakage inflates scores dishonestly."},
        {"type": "fill-blank", "text": "The gap between train and test performance defines ____.",
         "options": [], "correct_answer": "overfitting",
         "explanation": "A large gap means the model memorized the training data."},
    ],
    (6, 2): [
        {"type": "multiple-choice", "text": "MSE stands for mean ____ error.",
         "options": ["signed", "squared", "scaled", "sampled"], "correct_answer": "squared",
         "explanation": "It averages the squared residuals."},
        {"type": "multiple-choice", "text": "A perfect regression fit gives an MSE of:",
         "options": ["1", "0", "100", "-1"], "correct_answer": "0",
         "explanation": "No error means zero squared error."},
        {"type": "fill-blank", "text": "The square root of MSE, back in original units, is called ____.",
         "options": [], "correct_answer": "RMSE",
         "explanation": "Root mean squared error."},
    ],
    (6, 3): [
        {"type": "multiple-choice", "text": "Gradient descent updates a weight by:",
         "options": ["w + lr*grad", "w - lr*grad", "w * grad", "grad / w"],
         "correct_answer": "w - lr*grad",
         "explanation": "Step against the gradient scaled by the learning rate."},
        {"type": "multiple-choice", "text": "A learning rate that is too large tends to:",
         "options": ["converge fast and safely", "overshoot or diverge", "do nothing", "sort data"],
         "correct_answer": "overshoot or diverge",
         "explanation": "Big steps can jump past the minimum."},
        {"type": "fill-blank", "text": "The gradient points ____ (uphill/downhill); we subtract it.",
         "options": [], "correct_answer": "uphill",
         "explanation": "So subtracting it moves toward lower loss."},
    ],
    (6, 4): [
        {"type": "multiple-choice", "text": "Sigmoid maps any real number into:",
         "options": ["(0, 1)", "[-1, 1]", "[0, 100]", "integers"], "correct_answer": "(0, 1)",
         "explanation": "Making it usable as a probability."},
        {"type": "multiple-choice", "text": "sigmoid(0) equals:",
         "options": ["0", "0.5", "1", "-1"], "correct_answer": "0.5",
         "explanation": "1/(1+e^0) = 1/2."},
        {"type": "fill-blank", "text": "Logistic regression applies sigmoid to w·x + ____.",
         "options": [], "correct_answer": "b",
         "explanation": "The bias term b."},
    ],
    (6, 5): [
        {"type": "multiple-choice", "text": "Accuracy is misleading when classes are:",
         "options": ["balanced", "imbalanced", "numeric", "sorted"], "correct_answer": "imbalanced",
         "explanation": "Predicting the majority can score high yet be useless."},
        {"type": "multiple-choice", "text": "Accuracy is the fraction of predictions that are:",
         "options": ["positive", "correct", "negative", "large"], "correct_answer": "correct",
         "explanation": "correct / total."},
        {"type": "fill-blank", "text": "For rare-event detection, ____ often matters more than accuracy.",
         "options": [], "correct_answer": "recall",
         "explanation": "Recall measures how many true positives you catch."},
    ],
    # ===== Phase 7: Deep Learning =====
    (7, 1): [
        {"type": "multiple-choice", "text": "A single perceptron can separate data that is:",
         "options": ["any", "linearly separable", "circular", "random"],
         "correct_answer": "linearly separable",
         "explanation": "One neuron draws a single linear boundary."},
        {"type": "multiple-choice", "text": "The bias term lets a neuron:",
         "options": ["ignore inputs", "shift its threshold", "sort inputs", "add layers"],
         "correct_answer": "shift its threshold",
         "explanation": "Bias moves the decision boundary."},
        {"type": "fill-blank", "text": "A perceptron fires when w·x + b is >= ____.",
         "options": [], "correct_answer": "0",
         "explanation": "The step activation triggers at 0."},
    ],
    (7, 2): [
        {"type": "multiple-choice", "text": "ReLU(x) equals:",
         "options": ["min(0, x)", "max(0, x)", "|x|", "1/x"], "correct_answer": "max(0, x)",
         "explanation": "Passes positives, zeroes negatives."},
        {"type": "multiple-choice", "text": "Without a non-linear activation, stacked layers collapse to:",
         "options": ["one linear function", "a CNN", "a decision tree", "noise"],
         "correct_answer": "one linear function",
         "explanation": "Composed linear maps are still linear."},
        {"type": "fill-blank", "text": "Sigmoid and tanh suffer from ____ gradients when saturated.",
         "options": [], "correct_answer": "vanishing",
         "explanation": "Tiny gradients slow deep-network training."},
    ],
    (7, 3): [
        {"type": "multiple-choice", "text": "A dense layer turns an input vector into:",
         "options": ["a scalar", "a new vector", "a matrix", "a string"],
         "correct_answer": "a new vector",
         "explanation": "One activation per neuron."},
        {"type": "multiple-choice", "text": "The forward pass is used for:",
         "options": ["training only", "inference/prediction", "sorting", "loading data"],
         "correct_answer": "inference/prediction",
         "explanation": "Prediction is just forward propagation."},
        {"type": "fill-blank", "text": "Each neuron's output is activation(dot(w, inputs) + ____).",
         "options": [], "correct_answer": "bias",
         "explanation": "Weighted sum plus bias, then activation."},
    ],
    (7, 4): [
        {"type": "multiple-choice", "text": "Binary cross-entropy pairs naturally with which output?",
         "options": ["ReLU", "sigmoid", "argmax", "identity"], "correct_answer": "sigmoid",
         "explanation": "Sigmoid gives the probability BCE scores."},
        {"type": "multiple-choice", "text": "A confident and wrong prediction gives a BCE loss that is:",
         "options": ["near 0", "negative", "very large", "exactly 1"], "correct_answer": "very large",
         "explanation": "-log(p) explodes as p -> 0 for the true class."},
        {"type": "fill-blank", "text": "Next-token training of LLMs uses the ____-entropy loss.",
         "options": [], "correct_answer": "cross",
         "explanation": "Cross-entropy over the vocabulary distribution."},
    ],
    # ===== Phase 8: Frameworks =====
    (8, 1): [
        {"type": "multiple-choice", "text": "Reshaping a tensor keeps the total element count:",
         "options": ["larger", "smaller", "constant", "zero"], "correct_answer": "constant",
         "explanation": "2x3 and 6 hold the same 6 elements."},
        {"type": "multiple-choice", "text": "The #1 framework paper-cut is:",
         "options": ["shape mismatches", "slow imports", "long names", "comments"],
         "correct_answer": "shape mismatches",
         "explanation": "Misaligned tensor shapes break matmuls and layers."},
        {"type": "fill-blank", "text": "Collapsing a tensor to 1-D before a dense head is called ____.",
         "options": [], "correct_answer": "flatten",
         "explanation": "flatten() turns any shape into a vector."},
    ],
    (8, 2): [
        {"type": "multiple-choice", "text": "The chain rule multiplies the ____ derivatives along a chain.",
         "options": ["local", "global", "average", "random"], "correct_answer": "local",
         "explanation": "dy/dx = product of local derivatives."},
        {"type": "multiple-choice", "text": "In PyTorch, `loss.backward()` performs:",
         "options": ["a forward pass", "backpropagation", "data loading", "sorting"],
         "correct_answer": "backpropagation",
         "explanation": "It computes gradients via the chain rule."},
        {"type": "fill-blank", "text": "Products of many small local gradients cause ____ gradients.",
         "options": [], "correct_answer": "vanishing",
         "explanation": "And products of large ones cause exploding gradients."},
    ],
    (8, 3): [
        {"type": "multiple-choice", "text": "Between layers of size a and b there are:",
         "options": ["a+b params", "a*b weights + b biases", "a*b*b", "just b"],
         "correct_answer": "a*b weights + b biases",
         "explanation": "One weight per connection, one bias per output neuron."},
        {"type": "multiple-choice", "text": "Parameter count mainly drives a model's:",
         "options": ["color", "memory & capacity", "file name", "learning rate"],
         "correct_answer": "memory & capacity",
         "explanation": "It's how we compare a 7B vs 70B model."},
        {"type": "fill-blank", "text": "`sum(p.numel() for p in model.____())` counts PyTorch parameters.",
         "options": [], "correct_answer": "parameters",
         "explanation": "model.parameters() yields all tensors."},
    ],
    (8, 4): [
        {"type": "multiple-choice", "text": "The correct per-batch training order is:",
         "options": ["step, backward, forward", "zero_grad, forward, loss, backward, step",
                     "loss, step, forward", "backward, forward, step"],
         "correct_answer": "zero_grad, forward, loss, backward, step",
         "explanation": "Clear grads, predict, measure, backprop, update."},
        {"type": "multiple-choice", "text": "An epoch's loss is reported as the ____ of batch losses.",
         "options": ["sum", "mean", "max", "last"], "correct_answer": "mean",
         "explanation": "Average across the batches, not just the final one."},
        {"type": "fill-blank", "text": "Forgetting `zero_grad()` causes gradients to ____ across batches.",
         "options": [], "correct_answer": "accumulate",
         "explanation": "PyTorch sums grads unless you zero them."},
    ],
    # ===== Phase 9: Computer Vision =====
    (9, 1): [
        {"type": "multiple-choice", "text": "Which channel has the largest grayscale luminance weight?",
         "options": ["red", "green", "blue", "alpha"], "correct_answer": "green",
         "explanation": "0.587 for green vs 0.299 red, 0.114 blue."},
        {"type": "multiple-choice", "text": "The common image shape convention is:",
         "options": ["(width, height)", "(height, width, channels)", "(channels only)", "(pixels)"],
         "correct_answer": "(height, width, channels)",
         "explanation": "H x W x C for a colour image."},
        {"type": "fill-blank", "text": "Grayscale reduces three colour channels to ____ channel(s).",
         "options": [], "correct_answer": "1",
         "explanation": "A single luminance channel."},
    ],
    (9, 2): [
        {"type": "multiple-choice", "text": "With 'valid' padding, convolution output length is:",
         "options": ["len(signal)", "len(signal)-len(kernel)+1", "len(kernel)", "len(signal)*2"],
         "correct_answer": "len(signal)-len(kernel)+1",
         "explanation": "The kernel fits in that many positions."},
        {"type": "multiple-choice", "text": "In a CNN, the kernel weights are:",
         "options": ["fixed by hand", "learned", "random forever", "always 1"],
         "correct_answer": "learned",
         "explanation": "Training learns the filters."},
        {"type": "fill-blank", "text": "The core operation of a CNN is ____.",
         "options": [], "correct_answer": "convolution",
         "explanation": "Sliding a kernel to detect local patterns."},
    ],
    (9, 3): [
        {"type": "multiple-choice", "text": "Max pooling keeps, per window, the:",
         "options": ["minimum", "maximum", "mean", "first"], "correct_answer": "maximum",
         "explanation": "It preserves the strongest activation."},
        {"type": "multiple-choice", "text": "Pooling primarily:",
         "options": ["adds parameters", "downsamples", "sorts pixels", "adds colour"],
         "correct_answer": "downsamples",
         "explanation": "It reduces spatial resolution."},
        {"type": "fill-blank", "text": "A pooling window and stride of 2 roughly ____ the length.",
         "options": [], "correct_answer": "halves",
         "explanation": "Non-overlapping size-2 windows halve the dimension."},
    ],
    (9, 4): [
        {"type": "multiple-choice", "text": "Conv output size is floor((W - K + 2P)/S) + 1. P is:",
         "options": ["pixels", "padding", "pooling", "power"], "correct_answer": "padding",
         "explanation": "P is the padding added to each side."},
        {"type": "multiple-choice", "text": "Increasing stride S generally makes the output:",
         "options": ["larger", "smaller", "unchanged", "square"], "correct_answer": "smaller",
         "explanation": "Bigger steps downsample more."},
        {"type": "fill-blank", "text": "Padding that keeps the output the same size is called '____' padding.",
         "options": [], "correct_answer": "same",
         "explanation": "'same' vs 'valid' padding."},
    ],
    # ===== Phase 10: NLP =====
    (10, 1): [
        {"type": "multiple-choice", "text": "Lowercasing during tokenization collapses:",
         "options": ["numbers", "'The' and 'the'", "spaces", "vowels"],
         "correct_answer": "'The' and 'the'",
         "explanation": "Case-folding merges them into one token."},
        {"type": "multiple-choice", "text": "Modern LLMs typically tokenize using:",
         "options": ["whole words", "subword (BPE)", "characters only", "sentences"],
         "correct_answer": "subword (BPE)",
         "explanation": "Byte-pair encoding balances vocab size and coverage."},
        {"type": "fill-blank", "text": "Tokenization is step ____ of every NLP pipeline (a number).",
         "options": [], "correct_answer": "0",
         "explanation": "It's the very first transformation of raw text."},
    ],
    (10, 2): [
        {"type": "multiple-choice", "text": "Term frequency divides each token's count by:",
         "options": ["the vocab size", "the total tokens", "1", "the longest word"],
         "correct_answer": "the total tokens",
         "explanation": "tf(t) = count(t) / total tokens."},
        {"type": "multiple-choice", "text": "The bag-of-words model discards:",
         "options": ["word counts", "word order", "the vocabulary", "frequencies"],
         "correct_answer": "word order",
         "explanation": "Only counts remain, not sequence."},
        {"type": "fill-blank", "text": "TF-____ down-weights words common across all documents.",
         "options": [], "correct_answer": "IDF",
         "explanation": "Inverse document frequency."},
    ],
    (10, 3): [
        {"type": "multiple-choice", "text": "Cosine similarity mainly compares vectors by their:",
         "options": ["length", "direction", "sum", "count"], "correct_answer": "direction",
         "explanation": "It's magnitude-independent."},
        {"type": "multiple-choice", "text": "Cosine similarity of [1,1] and [2,2] is:",
         "options": ["0", "0.5", "1", "2"], "correct_answer": "1",
         "explanation": "Same direction -> similarity 1."},
        {"type": "fill-blank", "text": "RAG retrieval ranks documents by cosine similarity of their ____.",
         "options": [], "correct_answer": "embeddings",
         "explanation": "Vectors that place similar text close together."},
    ],
    (10, 4): [
        {"type": "multiple-choice", "text": "A 2-token n-gram is called a:",
         "options": ["unigram", "bigram", "trigram", "token"], "correct_answer": "bigram",
         "explanation": "n=2 is a bigram."},
        {"type": "multiple-choice", "text": "If n > number of tokens, the n-gram list is:",
         "options": ["all tokens", "empty", "one gram", "an error"], "correct_answer": "empty",
         "explanation": "No window of that size fits."},
        {"type": "fill-blank", "text": "N-grams add a little word-____ information back to bag-of-words.",
         "options": [], "correct_answer": "order",
         "explanation": "Contiguous runs preserve local order."},
    ],
    # ===== Phase 11: LLMs =====
    (11, 1): [
        {"type": "multiple-choice", "text": "Softmax outputs values that:",
         "options": ["sum to 1", "sum to 0", "are integers", "are negative"],
         "correct_answer": "sum to 1",
         "explanation": "It's a probability distribution."},
        {"type": "multiple-choice", "text": "We subtract max(z) before exp() in softmax for:",
         "options": ["speed", "numerical stability", "sorting", "smaller code"],
         "correct_answer": "numerical stability",
         "explanation": "It avoids exp overflow; the result is identical."},
        {"type": "fill-blank", "text": "An LLM's next-token distribution is produced by ____.",
         "options": [], "correct_answer": "softmax",
         "explanation": "Applied to the output logits."},
    ],
    (11, 2): [
        {"type": "multiple-choice", "text": "Attention scales dot-product scores by:",
         "options": ["1/d", "1/sqrt(d)", "d", "sqrt(d)"], "correct_answer": "1/sqrt(d)",
         "explanation": "Scaling keeps softmax from saturating."},
        {"type": "multiple-choice", "text": "Attention weights over the keys form a:",
         "options": ["single number", "probability distribution", "matrix inverse", "sorted list"],
         "correct_answer": "probability distribution",
         "explanation": "They are a softmax, so they sum to 1."},
        {"type": "fill-blank", "text": "Scaled dot-product attention is the core of the ____ architecture.",
         "options": [], "correct_answer": "transformer",
         "explanation": "Transformers stack attention layers."},
    ],
    (11, 3): [
        {"type": "multiple-choice", "text": "Raising the temperature makes sampling:",
         "options": ["more deterministic", "more random", "faster", "shorter"],
         "correct_answer": "more random",
         "explanation": "High T flattens the distribution."},
        {"type": "multiple-choice", "text": "Temperature is applied to the logits:",
         "options": ["after softmax", "before softmax", "never", "twice"],
         "correct_answer": "before softmax",
         "explanation": "Divide logits by T, then softmax."},
        {"type": "fill-blank", "text": "As temperature approaches 0, sampling approaches ____ (greedy) selection.",
         "options": [], "correct_answer": "greedy",
         "explanation": "It picks the argmax token."},
    ],
    (11, 4): [
        {"type": "multiple-choice", "text": "RAG grounds an LLM in your data by:",
         "options": ["retraining it", "retrieving relevant docs", "raising temperature", "pruning weights"],
         "correct_answer": "retrieving relevant docs",
         "explanation": "It fetches context to condition generation."},
        {"type": "multiple-choice", "text": "Retrieval is essentially a ____ search over vectors.",
         "options": ["nearest-neighbour", "binary", "depth-first", "linear regression"],
         "correct_answer": "nearest-neighbour",
         "explanation": "Find the closest embeddings to the query."},
        {"type": "fill-blank", "text": "Large-scale RAG uses approximate NN indexes like FAISS or ____.",
         "options": [], "correct_answer": "HNSW",
         "explanation": "Hierarchical navigable small-world graphs."},
    ],
    # ===== Phase 12: Production =====
    (12, 1): [
        {"type": "multiple-choice", "text": "Batching improves GPU:",
         "options": ["accuracy", "throughput", "color", "vocabulary"], "correct_answer": "throughput",
         "explanation": "Processing many inputs at once maximizes utilization."},
        {"type": "multiple-choice", "text": "The final batch of a stream is often:",
         "options": ["dropped", "ragged/smaller", "the largest", "empty"],
         "correct_answer": "ragged/smaller",
         "explanation": "Handle a smaller last chunk; don't drop it."},
        {"type": "fill-blank", "text": "Larger batches raise throughput but also increase memory and ____.",
         "options": [], "correct_answer": "latency",
         "explanation": "Requests wait longer to fill a big batch."},
    ],
    (12, 2): [
        {"type": "multiple-choice", "text": "In semantic versioning, a breaking change bumps the:",
         "options": ["patch", "minor", "major", "build"], "correct_answer": "major",
         "explanation": "major.minor.patch — major = breaking."},
        {"type": "multiple-choice", "text": "Version tuples compare:",
         "options": ["randomly", "lexicographically", "by length", "alphabetically only"],
         "correct_answer": "lexicographically",
         "explanation": "(2,0,0) > (1,9,9)."},
        {"type": "fill-blank", "text": "Versioning every model artifact supports ____ (rollbacks/audit).",
         "options": [], "correct_answer": "reproducibility",
         "explanation": "You can trace and roll back any prediction."},
    ],
    (12, 3): [
        {"type": "multiple-choice", "text": "When input/output stats change over time, that's called:",
         "options": ["drift", "batching", "pooling", "leakage"], "correct_answer": "drift",
         "explanation": "Data/concept drift degrades models silently."},
        {"type": "multiple-choice", "text": "A larger moving-average window smooths more but:",
         "options": ["lags more", "is faster", "adds noise", "needs a GPU"],
         "correct_answer": "lags more",
         "explanation": "It reacts slower to real changes."},
        {"type": "fill-blank", "text": "Detecting drift early is what triggers model ____.",
         "options": [], "correct_answer": "retraining",
         "explanation": "Refresh the model before users notice."},
    ],
    (12, 4): [
        {"type": "multiple-choice", "text": "Which status codes count as server errors?",
         "options": ["2xx", "3xx", "4xx", "5xx"], "correct_answer": "5xx",
         "explanation": "5xx = server errors; 4xx = client errors."},
        {"type": "multiple-choice", "text": "Error rate is best tracked per:",
         "options": ["color", "model version", "user name", "day of week only"],
         "correct_answer": "model version",
         "explanation": "So a bad deploy is caught fast."},
        {"type": "fill-blank", "text": "Error rate feeds alerting and automatic ____.",
         "options": [], "correct_answer": "rollbacks",
         "explanation": "A spike can trigger reverting the deploy."},
    ],
}
